### ISSUE TITLE
Expired auth presents a blank "Organizations" page

### ISSUE THREAD

**Issue by ahpook** [github-community-projects/internal-contribution-forks#118]
### Describe the bug

When my auth token has expired to the app, I'm still able to view the top level "organizations" page, but it's empty. The only way to fix this is to manually log out and back in.

### To Reproduce

1. Let an auth token expire (24h, I think?)
2. Go back to the app's top level page
3. Note the empty organizations page (see screenshot)

### Expected behavior

I should be prompted to do the auth / 2FA tapdance automatically

### Screenshots

![Image](https://github.com/github-community-projects/internal-contribution-forks/assets/56753/81d4d172-71b9-4720-bd01-2d001c083c25)

**Comment by ajhenry** [comment]
This is definitely something we've run into and I've tried to fix before with https://github.com/github-community-projects/internal-contribution-forks/pull/30

This is because the token only lives for ~12 hours afaik but we don't actually clear the session after that
