### ISSUE TITLE
README has dead link to app-manifest.yml

### ISSUE THREAD

**Issue by grossag** [github-community-projects/internal-contribution-forks#65]
The section https://github.com/github-community-projects/internal-contribution-forks?tab=readme-ov-file#github-app has a link:

There's an App manifest in the repo that lays out all the permissions and webhook events needed and can be found [here](https://github.com/github-community-projects/internal-contribution-forks/blob/main/app-manifest.yml).

but that file doesn't seem to exist anymore.

**Comment by ajhenry** [comment]
Whoops, that's definitely a dead link. Thanks for the heads up, I'll fix that!
